import { Produto } from "../produto";

const produtos: Produto [] = [
    { 
        id: 1,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
    {
        id: 2,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
    {
        id: 3,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
    { 
        id: 4,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
    {
        id: 5,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
    {
        id: 6,
        nome: 'Notebook Gamer Acer Nitro 5',
        descricao: 'O Acer Nitro 5 é um notebook gamer poderoso, ideal ...',
        marca: 'Acer',
        modelo: 'Nitro 5',
        imagem: 'https://example.com/acer-nitro-5.jpg',
        nota: 4.8,
        videoReview: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        tags: ['Baixou'],
        precoBase: 6499.99,
        menorPreco: 4850.90,
        maiorPreco: 9800.80,
        precoMedio: 6503.70,
        precoPromocional: 5999.99,
        especificacoes: {
            destaque: 'NVIDIA GeForce RTX 2060',
            Processador: 'Intel Core i5-930H',
            Memória: '16GB DDR4',
            Armazenamento: '512GB SSD',
            'Placa de Vídeo': 'NVIDIA GeForce RTX 2060',
            Tela: '15.6 Polegadas Full HD',
            Peso: '2.5 Kg',
        },
    },
]

export default produtos;